global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "nietzschenator"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "host.docker.internal:8081" ]
#      - targets: ["nietzschenator:8081"]

  - job_name: "redsecbot"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8080"]
#      - targets: ["redsecbot:8080"]
